# В формулах, переменная lvl заменяется на уровень оружия или брони

ARMOR:

    LEATHER_HELMET:
        max_level: 10
        eval_level_strange: lvl * 0.3
    IRON_HELMET:
        max_level: 10
        eval_level_strange: lvl * 0.3
    GOLD_HELMET:
        max_level: 10
        eval_level_strange: lvl * 0.3
    DIAMOND_HELMET:
        max_level: 10
        eval_level_strange: lvl * 0.3
    CHAINMAIL_HELMET:
        max_level: 10
        eval_level_strange: lvl * 0.3

    LEATHER_CHESTPLATE:
        max_level: 10
        eval_level_strange: lvl * 0.3
    IRON_CHESTPLATE:
        max_level: 10
        eval_level_strange: lvl * 0.3
    GOLD_CHESTPLATE:
        max_level: 10
        eval_level_strange: lvl * 0.3
    DIAMOND_CHESTPLATE:
        max_level: 10
        eval_level_strange: lvl * 0.3
    CHAINMAIL_CHESTPLATE:
        max_level: 10
        eval_level_strange: lvl * 0.3

    LEATHER_LEGGINGS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    IRON_LEGGINGS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    GOLD_LEGGINGS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    DIAMOND_LEGGINGS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    CHAINMAIL_LEGGINGS:
        max_level: 10
        eval_level_strange: lvl * 0.3

    LEATHER_BOOTS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    IRON_BOOTS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    GOLD_BOOTS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    DIAMOND_BOOTS:
        max_level: 10
        eval_level_strange: lvl * 0.3
    CHAINMAIL_BOOTS:
        max_level: 10
        eval_level_strange: lvl * 0.3

WEAPONS:

    BOW:
        max_level: 10
        eval_level_damage: 5 + lvl * 2

    WOOD_SWORD:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    STONE_SWORD:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    IRON_SWORD:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    GOLD_SWORD:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    DIAMOND_SWORD:
        max_level: 10
        eval_level_damage: 5 + lvl * 2

    WOOD_AXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    STONE_AXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    IRON_AXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    GOLD_AXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    DIAMOND_AXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2

    WOOD_PICKAXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    STONE_PICKAXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    IRON_PICKAXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    GOLD_PICKAXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2
    DIAMOND_PICKAXE:
        max_level: 10
        eval_level_damage: 5 + lvl * 2